APP1/urls.py
from django.urls import path
from . import views

app_name = 'APP1'

urlpatterns = [
    path("login/", views.login, name = "login"),
    # path("leads/", views.leads, name = "leads"),
    path("leads/", views.Leadlistview.as_view(), name = "leads"),
    # path("leads_details/<int:key>/", views.leads_detail, name = "lead_details"),
    path("leads_details/<int:pk>/", views.Leaddetailview.as_view(), name = "lead_details"),
    # path("leads_details/<int:pk>/update/", views.update_lead, name = "update_lead"),
    path("leads_details/<int:pk>/update/", views.Leadupdateview.as_view(), name = "update_lead"),
    # path("leads_details/<int:pk>/delete/", views.delete_lead, name = "delete_lead"),
    path("leads_details/<int:pk>/delete/", views.Leaddeleteview.as_view(), name = "delete_lead"),
    # path("create_lead/", views.new_lead, name = "new_lead")
    path("create_lead/", views.Leadcreateview.as_view(), name = "new_lead")
]

Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from APP1 import views

urlpatterns = [
    path("", views.Landingpageview.as_view(), name="Landing"),
    path("admin/", admin.site.urls),
    path("we/", views.Land.as_view(), name="Landing-1"), # Useless just to check LoginMixinsRequired
    path("APP1/", include("APP1.urls", namespace ="APP1NameSpace")),
    path("Agent/", include("Agent.urls", namespace ="AgentNameSpace")),
    path("login/", LoginView.as_view(), name='login'), #default loc template will be load from template/registration/login.html
    path("logout/", LogoutView.as_view(), name='logout'),
    path("signup/", views.Signupview.as_view(), name='signup')
]

if settings.DEBUG:
    # urlpatterns += (static(settings.STATIC_URL, document_root = settings.STATIC_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root = settings.STATIC_ROOT))

APP1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save

class User(AbstractUser):
    pass

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

# Create your models here.
class Pizza(models.Model):
    PizzaFlavor = models.CharField(max_length=50)
    topping = models.ForeignKey("toppings", on_delete=models.CASCADE)
    
    def __str__(self):
        return self.PizzaFlavor
    
class toppings(models.Model):
    topping_name = models.CharField(max_length=50)
    ingredients =  models.CharField(max_length=50)
    
    def __str__(self):
        return self.topping_name
    
class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=20)
    
    def __str__(self):
        return self.firstName
    def __del__(self):
        return f"{self.firstName} is deleted"
    
class Lead(models.Model):
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=20)
    age = models.IntegerField(blank = True, null = True)
    agent = models.ForeignKey(Agent, on_delete=models.CASCADE)
    
    def __str__(self):
        # return self.agent.firstName
        return self.firstName

def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(post_user_created_signal, sender=User)

APP1/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from . import models

User = get_user_model()

class create_form(forms.Form):
    firstName = forms.CharField(max_length=20)
    lastName = forms.CharField(max_length=20)
    age = forms.IntegerField()
    
class create_form_model(forms.ModelForm):
    class Meta:
        model = models.Lead
        fields = ("firstName", "lastName", "age", "agent")
        
class Customusercreationform(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}

APP1/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.mail import send_mail
# from django.contrib.auth.forms import UserCreationForm #Not using this
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic, View
from django.http import HttpResponse, HttpResponseRedirect
from . import models, forms

class Signupview(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = forms.Customusercreationform
    def get_success_url(self):
        return reverse("login")

class Landingpageview(generic.TemplateView):
    template_name = "landing.html"

class Land(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "landing.html")
    
def landing(request):
    return render(request, "landing.html")

def login(request):
    return render(request, "APP1/login.html")

class Leadlistview(LoginRequiredMixin, generic.ListView):
    template_name = "APP1/leads.html"
    queryset = models.Lead.objects.all()
    context_object_name = "leads"

def leads(request):
    leads = models.Lead.objects.all()
    data = { "leads": leads}
    return render(request, "APP1/leads.html", context = data)

class Leaddetailview(LoginRequiredMixin, generic.DetailView):
    template_name = "APP1/leads_details.html"
    queryset = models.Lead.objects.all()
    context_object_name = "leads"

def leads_detail(request, key):
    leads = models.Lead.objects.get(id=key)
    data = { "leads": leads,
             "test": key}
    return render(request, "APP1/leads_details.html", context = data)

class Leadcreateview(LoginRequiredMixin, generic.CreateView):
    template_name = "APP1/create_form.html"
    form_class = forms.create_form_model
    def get_success_url(self):
        return reverse("APP1NameSpace:leads")
    
    def form_valid(self, form):
        send_mail(subject="A Lead has been created",
                  message="GO TO site to check the lead",
                  from_email="test@test.com",
                  recipient_list=["test2@test.com"])
        return super(Leadcreateview,self).form_valid(form)

def new_lead(request):
    form1 = forms.create_form_model()
    if request.method == "POST":
        form1 = forms.create_form_model(request.POST)
        if form1.is_valid():
            form1.save()
            # webpage = reverse("leads")
            # return HttpResponseRedirect(webpage) this can also be used but preffered when sending data
            return redirect("/APP1/leads")
    data = {"form": form1}
    return render(request, "APP1/create_form.html", context = data)

# the below function is same but using normal form.

# def new_lead(request):
#     form = forms.create_form()
#     if request.method == "POST":
#         form = forms.create_form(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             firstName = form.cleaned_data["firstName"]
#             lastName = form.cleaned_data["lastName"]
#             age = form.cleaned_data["age"]
#             agent = models.Agent.objects.get(id=1)
#             models.Lead.objects.create(firstName = firstName,
#                                        lastName = lastName,
#                                        age = age,
#                                        agent = agent)
#             # webpage = reverse("leads")
#             # return HttpResponseRedirect(webpage)
#             return redirect("/APP1/leads")
#     data = {"form": form}
#     return render(request, "APP1/create_form.html", context = data)

class Leadupdateview(LoginRequiredMixin, generic.UpdateView):
    queryset = models.Lead.objects.all()
    form_class = forms.create_form_model
    template_name = "APP1/update_form.html"
    def get_success_url(self):
        return reverse("APP1NameSpace:leads")
        # return redirect("/APP1/leads") this doesnt work in class

def update_lead(request, pk):
    lead = models.Lead.objects.get(id=pk)
    form = forms.create_form_model(instance=lead)
    if request.method == "POST":
        form = forms.create_form_model(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/APP1/leads")
    data = {"form": form,
            "lead": lead}
    return render(request, "APP1/update_form.html", context = data)

# below function is same as above about updating

# def update_lead(request, pk):
#     lead = models.Lead.objects.get(id=pk)
#     form = forms.create_form()
#     if request.method == "POST":
#         form = forms.create_form(request.POST)
#         if form.is_valid():
#             lead.firstName = form.cleaned_data["firstName"]
#             lead.lastName = form.cleaned_data["lastName"]
#             lead.age = form.cleaned_data["age"]
#             lead.agent = lead.agent
#             lead.save()
#             return redirect("/APP1/leads")
#     data = {"form": form,
#             "lead": lead}
#     return render(request, "APP1/update_form.html", context = data)

class Leaddeleteview(LoginRequiredMixin, generic.DeleteView):
    template_name = "APP1/delete_form.html"
    queryset = models.Lead.objects.all()
    def get_success_url(self):
        return reverse("APP1NameSpace:leads")

def delete_lead(request, pk):
    lead = models.Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/APP1/leads")

APP1/templates/APP1/create_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Form</title>
  </head>
  <body>
    <h1>Create New Lead</h1>
    <form>{{form.as_p}}</form>
  </body>
</html>

APP1/templates/APP1/delete_form.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Form</title>
  </head>
  <body>
    <h1>Are you sure you want to delete this Lead?</h1>

    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button type="submit">Submit Form</button>
    </form>
  </body>
</html>

APP1/templates/APP1/leads.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between items-center border-between border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Leads</h1>
      </div>

      <div>
        <a class="text-gray-500 hover:text-blue-500" href="/APP1/create_lead"
          >Create a New Lead</a
        >
      </div>
    </div>
    <hr />
    <div class="flex flex-wrap -m-4">
      {% for lead in leads%}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{lead.firstName}} {{lead.lastName}}
            </h2>
            <p class="leading-relaxed text-base">
              Blue bottle crucifix vinyl post-ironic four dollar toast vegan
              taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a
              href="/APP1/leads_details/{{lead.id}}"
              class="mt-3 text-indigo-500 inline-flex items-center"
            >
              View this Lead
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}

APP1/templates/APP1/leads_details.html
{% extends "base.html" %} {% block content%}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{leads.firstName}} {{leads.lastName}}
        </h1>
        <div class="flex mb-4">
          <a
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Description</a
          >
          <a
            href="/APP1/leads_details/{{leads.id}}/delete"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Delete</a
          >
          <a
            href="{% url 'APP1NameSpace:update_lead' leads.id %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Update</a
          >
        </div>
        <p class="leading-relaxed mb-4">
          This contains the Bio of the Lead and Agent Description.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{leads.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Agent</span>
          <span class="ml-auto text-gray-900"
            >{{leads.agent.firstName}} {{leads.agent.lastName}}</span
          >
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell Phone</span>
          <span class="ml-auto text-gray-900">+92334122344</span>
        </div>
        <div class="flex">
          <button
            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Button
          </button>
          <button
            class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4"
          >
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-5 h-5"
              viewBox="0 0 24 24"
            >
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
              ></path>
            </svg>
          </button>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>

{% endblock %}

APP1/templates/APP1/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Project</title>
  </head>
  <body>
    <h>LOOK</h>
  </body>
</html>

APP1/templates/APP1/update_form.html
{% extends "base.html" %} {% block content%}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{leads.firstName}} {{leads.lastName}}
        </h1>
        <div class="flex mb-4">
          <a href="{% url "APP1NameSpace:lead_details" lead.id%}"
          class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Description</a
          >
          <a
            href="/APP1/leads_details/{{lead.id}}/delete"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Delete</a
          >
          <a
            href="{% url "APP1NameSpace:update_lead" lead.id%}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Update</a
          >
        </div>
        <form method="post">
          {% csrf_token %} {{form.as_p}}
          <button type="submit">Submit Form</button>
        </form>
        <a href="/APP1/leads_details/{{lead.id}}/delete" class="w-1/2 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
          Delete
        </a>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>

{% endblock %}