APP1/urls.py
from django.urls import path
from . import views

app_name = 'APP1'

urlpatterns = [
    path("login/", views.login, name = "login"),
    # path("leads/", views.leads, name = "leads"),
    path("leads/", views.Leadlistview.as_view(), name = "leads"),
    # path("leads_details/<int:key>/", views.leads_detail, name = "lead_details"),
    path("leads_details/<int:pk>/", views.Leaddetailview.as_view(), name = "lead_details"),
    # path("leads_details/<int:pk>/update/", views.update_lead, name = "update_lead"),
    path("leads_details/<int:pk>/update/", views.Leadupdateview.as_view(), name = "update_lead"),
    # path("leads_details/<int:pk>/delete/", views.delete_lead, name = "delete_lead"),
    path("leads_details/<int:pk>/delete/", views.Leaddeleteview.as_view(), name = "delete_lead"),
    # path("create_lead/", views.new_lead, name = "new_lead")
    path("create_lead/", views.Leadcreateview.as_view(), name = "new_lead")
]

Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from APP1 import views

urlpatterns = [
    path("", views.Landingpageview.as_view(), name="Landing"),
    path("admin/", admin.site.urls),
    path("we/", views.Land.as_view(), name="Landing-1"), # Useless just to check LoginMixinsRequired
    path("APP1/", include("APP1.urls", namespace ="APP1NameSpace")),
    path("Agent/", include("Agent.urls", namespace ="AgentNameSpace")),
    path("login/", LoginView.as_view(), name='login'), #default loc template will be load from template/registration/login.html
    path("logout/", LogoutView.as_view(), name='logout'),
    path("signup/", views.Signupview.as_view(), name='signup')
]

if settings.DEBUG:
    # urlpatterns += (static(settings.STATIC_URL, document_root = settings.STATIC_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root = settings.STATIC_ROOT))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DJ CRM</title>
    <link href="{% static 'script.js' %}" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    {% include "navbar.html" %} {% block content %} {% include "script.html" %}
    {% endblock %}
  </body>
</html>

templates/landing.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-5 py-24 items-center justify-center flex-col"
  >
    <img
      class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded"
      alt="hero"
      src="https://dummyimage.com/720x600"
    />
    <div class="text-center lg:w-2/3 w-full">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900"
      >
        CRM Builts with Django
      </h1>
      <p class="mb-8 leading-relaxed">This CRM helps you manage your Leads.</p>
      <div class="flex justify-center">
        <button
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"
        >
          Button
        </button>
        <button
          class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"
        >
          Button
        </button>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div
      class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
    >
      <a
        class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          stroke="currentColor"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
          viewBox="0 0 24 24"
        >
          <path
            d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
          ></path>
        </svg>
        <span class="ml-3 text-xl">DJ CRM</span>
      </a>
      
        <nav
          class="md:ml-auto flex flex-wrap items-center text-base justify-center"
        >
        
        <a href="{% url "APP1NameSpace:leads" %}" class="mr-5 hover:text-gray-900">Leads</a>
        {% if not request.user.is_authenticated%}
          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">SignUp</a>
        {% endif %}
        </nav>
      {% if request.user.is_authenticated %}
        You logged in as {{request.user.username}}
        <a
          href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Logout
          <svg
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            class="w-4 h-4 ml-1"
            viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% else %}
        <a
          href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Login
          <svg
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            class="w-4 h-4 ml-1"
            viewBox="0 0 24 24">
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </a>
      {% endif %}
    </div>
  </header>

templates/script.html
<script>
  console.log("Hello");
</script>