APP1/urls.py
from django.urls import path
from . import views

app_name = 'APP1'

urlpatterns = [
    path("login/", views.login, name = "login"),
    # path("leads/", views.leads, name = "leads"),
    path("leads/", views.Leadlistview.as_view(), name = "leads"),
    # path("leads_details/<int:key>/", views.leads_detail, name = "lead_details"),
    path("leads_details/<int:pk>/", views.Leaddetailview.as_view(), name = "lead_details"),
    # path("leads_details/<int:pk>/update/", views.update_lead, name = "update_lead"),
    path("leads_details/<int:pk>/update/", views.Leadupdateview.as_view(), name = "update_lead"),
    # path("leads_details/<int:pk>/delete/", views.delete_lead, name = "delete_lead"),
    path("leads_details/<int:pk>/delete/", views.Leaddeleteview.as_view(), name = "delete_lead"),
    # path("create_lead/", views.new_lead, name = "new_lead")
    path("create_lead/", views.Leadcreateview.as_view(), name = "new_lead")
]

Agent/urls.py
from django.urls import path
from . import views

app_name = 'Agent'

urlpatterns = [
    path("agents-list/", views.Agentlistview.as_view(), name="agent-list"),
    path("agents-create/", views.Agentcreateview.as_view(), name="agent-create"),
    path("check/", views.check),
]

Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from APP1 import views

urlpatterns = [
    path("", views.Landingpageview.as_view(), name="Landing"),
    path("admin/", admin.site.urls),
    path("we/", views.Land.as_view(), name="Landing-1"), # Useless just to check LoginMixinsRequired
    path("APP1/", include("APP1.urls", namespace ="APP1NameSpace")),
    path("Agent/", include("Agent.urls", namespace ="AgentNameSpace")),
    path("login/", LoginView.as_view(), name='login'), #default loc template will be load from template/registration/login.html
    path("logout/", LogoutView.as_view(), name='logout'),
    path("signup/", views.Signupview.as_view(), name='signup')
]

if settings.DEBUG:
    # urlpatterns += (static(settings.STATIC_URL, document_root = settings.STATIC_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root = settings.STATIC_ROOT))

Agent/models.py
from django.db import models

# Create your models here.

Agent/forms.py
from APP1 import models
from django import forms

class create_form_agent(forms.ModelForm):
    class Meta:
        model = models.Agent
        fields = ("user", "firstName", "lastName")

Agent/views.py
from django.shortcuts import render
from django.urls import reverse
from django.views import generic
from APP1 import models
from . import forms

class Agentlistview(generic.ListView):
    template_name = "Agent/agent-list.html"
    context_object_name = "agents"
    
    def get_queryset(self):
        return models.Agent.objects.all()
    
class Agentcreateview(generic.CreateView):
    template_name = "Agent/agent-create.html"
    form_class = forms.create_form_agent
    
    def get_success_url(self):
        return reverse("AgentNameSpace:agent-list")
    
    def form_valid(self, form):
        agent = form.save(commit=False)
        agent.organization = self.request.user.userprofile
        agent.save()
        return super(Agentcreateview, self).form_valid(form)
    
def check(request):
    agent = models.Agent.objects.get(id=1)
    leads = agent.lead_set.all()
    print(agent.leads[0].firstName) # Agent has multiple leads thats why simple "agent.lead.firstName" doesn't exist.
    return render(request, "landing.html")

Agent/templates/Agent/agent-create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Form</title>
  </head>
  <body>
    <h1>Create New Agent</h1>

    <form method="post">
      {% csrf_token %} {{form.as_p}}
      <button type="submit">Submit Form</button>
    </form>
  </body>
</html>

Agent/templates/Agent/agent-list.html
{% extends "base.html" %} {% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between items-center border-between border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Agents</h1>
      </div>

      <div>
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'AgentNameSpace:agent-create' %}"
          >Create a New Agent</a
        >
      </div>
    </div>
    <hr />
    <div class="flex flex-wrap -m-4">
      {% for agent in agents%}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div
          class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col"
        >
          <div
            class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0"
          >
            <svg
              fill="none"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-8 h-8"
              viewBox="0 0 24 24"
            >
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
              {{agent.firstName}} {{agent.lastName}}
            </h2>
            <p class="leading-relaxed text-base">
              Blue bottle crucifix vinyl post-ironic four dollar toast vegan
              taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a href="#" class="mt-3 text-indigo-500 inline-flex items-center">
              View this Agent
              <svg
                fill="none"
                stroke="currentColor"
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                class="w-4 h-4 ml-2"
                viewBox="0 0 24 24"
              >
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock %}